definitions:
  entity.User:
    properties:
      address:
        type: string
      blood_type:
        type: string
      created_at:
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      phone_number:
        type: string
      profile_photo:
        type: string
      rhesus:
        type: string
      role:
        type: string
      updated_at:
        type: string
    type: object
  handler.EducationResponse:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      image:
        type: string
      title:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
  handler.GoogleLoginRequest:
    properties:
      code:
        type: string
    type: object
  handler.HistoryResponse:
    properties:
      blood_request_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      image_donor:
        type: string
      next_donation:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  handler.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/entity.User'
    type: object
  handler.ResetPasswordRequest:
    properties:
      email:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/forgot-password:
    post:
      consumes:
      - application/json
      description: RequestPasswordReset
      parameters:
      - description: Request Password Reset
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: RequestPasswordReset
      tags:
      - Auth
  /api/auth/google/login:
    post:
      consumes:
      - application/json
      description: Google login
      parameters:
      - description: Google login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.GoogleLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Google login
      tags:
      - Auth
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a user
      tags:
      - Auth
  /api/auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register a new user
      parameters:
      - default: Fahrul
        description: Name
        in: formData
        name: name
        required: true
        type: string
      - default: example@example.com
        description: Email
        in: formData
        name: email
        required: true
        type: string
      - default: fahrul123
        description: Password
        in: formData
        name: password
        required: true
        type: string
      - default: patient
        description: Role
        in: formData
        name: role
        required: true
        type: string
      - default: "2000-01-02"
        description: Date of Birth
        format: date-time
        in: formData
        name: date_of_birth
        required: true
        type: string
      - default: "1234567890"
        description: Phone Number
        in: formData
        name: phone_number
        required: true
        type: string
      - description: Profile Photo
        in: formData
        name: profile_photo
        type: file
      - default: male
        description: Gender
        in: formData
        name: gender
        required: true
        type: string
      - default: Jakarta
        description: Address
        in: formData
        name: address
        required: true
        type: string
      - default: AB
        description: Blood Type
        in: formData
        name: blood_type
        type: string
      - default: +
        description: Rhesus
        in: formData
        name: rhesus
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Auth
  /api/education:
    delete:
      consumes:
      - application/json
      description: Delete education
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete education
      tags:
      - Education
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Post a new Education
      parameters:
      - description: Image
        in: formData
        name: image
        required: true
        type: file
      - default: Donora menang juara 1 di GSC tingkat international 2025
        description: Title
        in: formData
        name: title
        required: true
        type: string
      - default: This is
        description: Content
        in: formData
        name: content
        required: true
        type: string
      - default: pendonor
        description: Type
        in: formData
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.EducationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new Education
      tags:
      - Education
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: Update education
      parameters:
      - default: Donora menang juara 1 di GSC tingkat international 2025
        description: Title
        in: formData
        name: title
        required: true
        type: string
      - description: Image
        in: formData
        name: image
        required: true
        type: file
      - default: Alhamdulillah
        description: Content
        in: formData
        name: content
        required: true
        type: string
      - default: patient
        description: Type
        in: formData
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.EducationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update education
      tags:
      - Education
  /api/educations:
    get:
      consumes:
      - application/json
      description: Get All and get by id and type with params
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.EducationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Education
      tags:
      - Education
  /api/educations-pendonor:
    get:
      consumes:
      - application/json
      description: Get Education Pendonor
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.EducationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Education Pendonor
      tags:
      - Education
  /api/educations/pencari-donor:
    get:
      consumes:
      - application/json
      description: Get Education Pencari Donor
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.EducationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Education Pencari Donor
      tags:
      - Education
  /api/history:
    get:
      consumes:
      - application/json
      description: Retrieves a list of history records for a given user ID.
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.HistoryResponse'
            type: array
        "400":
          description: Invalid user ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user history
      tags:
      - History
    post:
      consumes:
      - multipart/form-data
      description: Create a new History
      parameters:
      - description: Image Donor
        in: formData
        name: image_donor
        required: true
        type: file
      - description: User ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: Blood Request ID
        in: formData
        name: blood_request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create History
      tags:
      - History
  /api/history/latest:
    get:
      consumes:
      - application/json
      description: Retrieves the latest history record for a given user ID.
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Latest donation date
          schema:
            type: string
        "400":
          description: Invalid user ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get latest history
      tags:
      - History
  /api/history/next:
    get:
      consumes:
      - application/json
      description: Retrieves the next scheduled donation date for the specified user.
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Next donation date
          schema:
            type: string
        "400":
          description: Invalid user ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get next donation date
      tags:
      - History
  /api/upload-evidence:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Upload Evidence
      parameters:
      - description: Image
        in: formData
        name: image
        required: true
        type: file
      - default: "1"
        description: User ID
        in: formData
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload Evidence
      tags:
      - Upload Evidence
swagger: "2.0"
